[package]
name = "test-quinn"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rustls = { version = "0.23.19", features = ["ring"]}
quinn = "0.11.6"
rcgen = "0.13.1"
